default: &default
  adapter: postgresql # Use PostgreSQL as the database
  encoding: unicode # Unicode encoding for multilingual support
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %> # Maximum number of connections per thread

development:
  <<: *default
  database: construction_management_development # Database name for the development environment

test:
  <<: *default
  database: construction_management_test # Database name for the test environment

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %> # Use DATABASE_URL for production
